.TH "QwtPickerMachine" 3 "Tue Nov 20 2012" "Version 5.2.3" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtPickerMachine \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qwt_picker_machine\&.h>\fP
.PP
Inherited by \fBQwtPickerClickPointMachine\fP, \fBQwtPickerClickRectMachine\fP, \fBQwtPickerDragPointMachine\fP, \fBQwtPickerDragRectMachine\fP, and \fBQwtPickerPolygonMachine\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBCommand\fP { \fBBegin\fP, \fBAppend\fP, \fBMove\fP, \fBEnd\fP }"
.br
.ti -1c
.RI "typedef QList< \fBCommand\fP > \fBCommandList\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~QwtPickerMachine\fP ()"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "void \fBsetState\fP (int)"
.br
.ti -1c
.RI "int \fBstate\fP () const "
.br
.ti -1c
.RI "virtual CommandList \fBtransition\fP (const \fBQwtEventPattern\fP &, const QEvent *)=0"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBQwtPickerMachine\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
A state machine for \fBQwtPicker\fP selections\&. 

\fBQwtPickerMachine\fP accepts key and mouse events and translates them into selection commands\&.
.PP
\fBSee also:\fP
.RS 4
\fBQwtEventPattern::MousePatternCode\fP, \fBQwtEventPattern::KeyPatternCode\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt User's Guide from the source code\&.
